services:
  - type: web
    name: college-attendance-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn college_attendance.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./college_attendance.db 